openai_apikey1="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"
openai_apibase="https://api.groq.com/openai/v1"
youtube_apikey="AIzaSyAR4ib24FZELpW90q08-A-Qpqr65f7ydo8"
YOUTUBE_API_SERVICE_NAME = "youtube"
YOUTUBE_API_VERSION = "v3"
host="db.evdrexfpqtdntbcjftwx.supabase.co"
port=5432
database="postgres"
user="postgres"
password="TharunRaghu123"
openai_apikey2= "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"